name: Run Tests and Coverage

on:
  pull_request:
    branches:
      - main     

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
       pip3 install -r requirements.txt

    - name: Run tests and coverage
      run: |
        pytest --cache-clear --cov > pytest-coverage.txt

    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2