name: Run Tests and Coverage

on:
  pull_request:
    branches:
      - main     

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
       pip3 install -r requirements.txt

    - name: Run tests and coverage
      run: |
        pytest --cov | sed -n '/Name\s*Stmts\s*Miss\s*Cover\s*$/,$p' > coverage.txt
        ls -l
        cat coverage.txt

    - name: Comment on PR with coverage
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('coverage.txt', 'utf8');
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Coverage Report:\n${output}`
          });